apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mini-twitter-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          # Frontend en la ra√≠z
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mini-twitter-frontend
                port:
                  number: 80
          # Backend en /backend
          - path: /backend/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mini-twitter-backend
                port:
                  number: 8000
